### PR TITLE
Number of fixes (each has their own pull req)

### PR DESCRIPTION
**Pull request by xsacha**
Number of changes.
Each have their own pull request now.

### CODE REVIEW

**Comment by dpmcmlxxvi** [comment]
Looks good. Have you run the suite of tests to confirm no breaks? I will do so myself soon and if no problems come will accept.

**Comment by xsacha** [comment]
I didn't run them but figured it would not be too hard to do so. I'll try today if you want.

**Comment by xsacha** [comment]
Would it help if I split out each of the changes in to separate pull requests?
I added a few new changes:
- updating shared_ptr to fix googletest error;
- fixing a warning (treated as error);
- giving an option to disable libxml2 and;
- allowing the cmakelists to be imported as a sub-project from another cmakelists

**Comment by dpmcmlxxvi** [comment]
It would help. I'm juggling a few projects and haven't had time to test these changes but will as soon as I can.

**Comment by xsacha** [comment]
Sure. Just pull them as you test :)
All working fine here on Linux+Windows+Android.

**Comment by dpmcmlxxvi** [comment]
Apologies for the delay in merging. Testing and merging individual PRs currently.

**Pull request closed without merging**
